replicaCount: 1

image:
  repository: your-registry/freefem-custom
  tag: "4.9"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 2Gi

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi

configMap:
  enabled: true
  data:
    freefem-script.edp: |
      // Your FreeFEM++ script here
      mesh Th = square(20, 20);
      fespace Vh(Th, P1);
      Vh u, v;
      solve Poisson(u, v) = 
        int2d(Th)(dx(u)*dx(v) + dy(u)*dy(v))
        - int2d(Th)(1*v)
        + on(1, 2, 3, 4, u=0);
      plot(u);
