apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freefem.fullname" . }}
  labels:
    {{- include "freefem.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "freefem.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "freefem.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["FreeFem++"]
          args: ["/scripts/freefem-script.edp"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: data
              mountPath: /freefem/data
      volumes:
        - name: scripts
          configMap:
            name: {{ include "freefem.fullname" . }}-configmap
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "freefem.fullname" . }}-pvc
