apiVersion: v1
kind: Service
metadata:
  name: {{ include "freefem.fullname" . }}
  labels:
    {{- include "freefem.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "freefem.selectorLabels" . | nindent 4 }}
